<a href="https://colab.research.google.com/github/rererheaaa/csst-101/blob/main/Abillonar%2C_Rhea_Carlizette_T_CSST101(COURSE_ENROLLMENT)EXERCISE3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Create the Student Database**

In [2]:
students <- data.frame(
    Student_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
    Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
    Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
    Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
    Prerequisite = c("Yes","No")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         No
5 S005       65                68         70         Yes
6 S006       85                90         91         No
7 S007       74                73         76         Yes
8 S008       82                79         85         No

**2. Explore the Data**

In [3]:
nrow(students)
ncol(students)
max(students$Programming_Grade)
max(students$Attendance)
max(students$Math_Grade)
mean(students$Attendance)
min(students$Math_Grade)

[1] 8

[1] 5

[1] 91

[1] 95

[1] 90

[1] 84.625

[1] 68

**3. Enter a Student ID**

In [4]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S002
[1] "S002"

**4. Search the Data Frame**

In [5]:
student <- students[
  students$Student_ID == student_id,
]
student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
2 S002       72                70         80         No

**5. Check if the Students Exists**

In [6]:
student <- students[
  students$Student_ID == student_id,
]
if (nrow(student) == 0) {
  print("Student ID not found.")
} else {
  print(student)
}

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
2       S002                72         70         80           No

**6. Extract Student Information**

In [7]:
programming <- student$Programming_Grade
math <- student$Math_Grade
attendance <- student$Attendance
prereq <- student$Prerequisite

cat("Programming Grade:", programming)
cat("\nMath Grade:", math)
cat("\nAttendance:", attendance, "%")
cat("\nPrerequisite:", prereq)

Programming Grade: 72
Math Grade: 70
Attendance: 80 %
Prerequisite: No

**7. Implement the Rules**

In [8]:
if (programming >= 80 &&
    math >= 75 &&
    attendance >= 80 &&
    prereq == "Yes") {

  classification <- "Eligible"

} else if (programming >= 75 &&
           math >= 70 &&
           attendance >= 75) {

  classification <- "Conditionally Eligible"

} else {

  classification <- "Not Eligible"
}

cat("\nClassification:", classification)

Classification: Not Eligible

**8. Apply the Function to All Students**

In [9]:
check_eligibility <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    return("Eligible")

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    return("Conditionally Eligible")

  } else {

    return("Not Eligible")
  }
}

students$Classification <- mapply(
  check_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         No
5 S005       65                68         70         Yes
6 S006       85                90         91         No
7 S007       74                73         76         Yes
8 S008       82                79         85         No
  Classification
1 Eligible
2 Not Eligible
3 Eligible
4 Conditionally Eligible
5 Not Eligible
6 Conditionally Eligible
7 Not Eligible
8 Conditionally Eligible

**9. Create Recommendation Rules**

In [10]:
recommendation <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    return("Highly Recommended")

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    return("Recommended with Improvement")

  } else {

    return("Needs Improvement")
  }
}

students$Recommendation <- mapply(
  recommendation,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         No
5 S005       65                68         70         Yes
6 S006       85                90         91         No
7 S007       74                73         76         Yes
8 S008       82                79         85         No
  Classification         Recommendation
1 Eligible               Highly Recommended
2 Not Eligible           Needs Improvement
3 Eligible               Highly Recommended
4 Conditionally Eligible Recommended with Improvement
5 Not Eligible           Needs Improvement
6 Conditionally Eligible Recommended with Improvement
7 Not Eligible           Needs Improvement
8 Conditionally Eligible Recommended with Improvement

**Final Output**

In [11]:
# ASK FOR STUDENT ID
student_id <- readline("Enter Student ID: ")

# FIND STUDENT
student <- students[students$Student_ID == student_id, ]

if (nrow(student) == 0) {

  cat("\nStudent not found.\n")

} else {

  # EXTRACT STUDENT INFORMATION
  programming <- student$Programming_Grade
  math <- student$Math_Grade
  attendance <- student$Attendance
  prereq <- student$Prerequisite

  # IMPLEMENT RULES
  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    classification <- "Eligible"

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    classification <- "Conditionally Eligible"

  } else {

    classification <- "Not Eligible"
  }

  # RECOMMENDATION RULES
  if (classification == "Eligible") {

    recommendation <- "Proceed with enrollment"

  } else if (classification == "Conditionally Eligible") {

    recommendation <- "Consult academic adviser"

  } else {

    recommendation <- "Not recommended for enrollment"
  }

  # FINAL OUTPUT
  cat("\n==========================================\n")
  cat("          COURSE ENROLLMENT ADVISER\n")
  cat("==========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", programming, "\n")
  cat("Math Grade:", math, "\n")
  cat("Attendance:", attendance, "%\n")
  cat("Prerequisite:", prereq, "\n\n")

  cat("Enrollment Status:\n")
  cat(classification, "\n\n")

  cat("Recommendation:\n")
  cat(recommendation, "\n\n")

  cat("==========================================\n")
}

Enter Student ID: S002

==========================================
          COURSE ENROLLMENT ADVISER
==========================================

Student ID: S002

Programming Grade: 72
Math Grade: 70
Attendance: 80 %
Prerequisite: No

Enrollment Status:
Not Eligible

Recommendation:
Not recommended for enrollment

==========================================